/*******************************************************************************
* Copyright (C) 2019-2023 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// nilm_seq2point_regress
// This file was @generated by ai8xize.py --test-dir ../msdk/ --prefix nilm_seq2point_regress --checkpoint-file ../ai8x-training/logs/2024.05.21-170228/qat_best_quantized.pth.tar --config-file networks/ai85-nilm-seq2point-regress-v2.yaml --sample-input ../ai8x-training/logs/2024.05.21-170228/sample_ukdale_small_regress.npy --overwrite --device MAX78000 --timer 0 --display-checkpoint --verbose

// DO NOT EDIT - regenerate this file instead!

// Configuring 9 layers
// Input data: HWC
// Layer 0: 1x100, no pooling, conv1d with kernel size 9, stride 1, pad 0, ReLU, 32x92 output
// Layer 1: 32x92, no pooling, conv1d with kernel size 8, stride 1, pad 0, ReLU, 32x85 output
// Layer 2: 32x85, max pool 2 with stride 2, conv1d with kernel size 6, stride 1, pad 0, ReLU, 48x37 output
// Layer 3: 48x37, max pool 2 with stride 2, conv1d with kernel size 5, stride 1, pad 0, ReLU, 64x14 output
// Layer 4: 64x14, no pooling, conv1d with kernel size 5, stride 1, pad 0, ReLU, 64x10 output
// Layer 5: 64x10, avg pool 2 with stride 2, conv1d with kernel size 4, stride 1, pad 1, ReLU, 32x4 output
// Layer 6: 32x4x1 flattened to 128x1x1, no pooling, linear, ReLU, 64x1x1 output
// Layer 7: 64x1x1, no pooling, linear, no activation, 10x1x1 output
// Layer 8: 64x1x1, no pooling, linear, no activation, 25x1x1 output

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
	// Acknowledge interrupt to all quadrants
	*((volatile uint32_t *) 0x50100000) &= ~((1<<12) | 1);
	*((volatile uint32_t *) 0x50500000) &= ~((1<<12) | 1);
	*((volatile uint32_t *) 0x50900000) &= ~((1<<12) | 1);
	*((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | 1);

	CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
	cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
	cnn_time = 1;
#endif
}

int cnn_continue(void)
{
	cnn_time = 0;

	*((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

	return CNN_OK;
}

int cnn_stop(void)
{
	*((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

	return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
	while (n-- > 0) {
		*dst++ = *src++;
	}
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
	uint32_t len;
	volatile uint32_t *addr;
	const uint32_t *ptr = kernels;

	while ((addr = (volatile uint32_t *) *ptr++) != 0) {
		*((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
		len = *ptr++;
		while (len-- > 0)
			*addr++ = *ptr++;
	}

	return CNN_OK;
}

static const uint8_t bias_0[] = BIAS_0;
static const uint8_t bias_1[] = BIAS_1;
static const uint8_t bias_2[] = BIAS_2;
static const uint8_t bias_3[] = BIAS_3;

static void memcpy_8to32(uint32_t *dst, const uint8_t *src, int n)
{
	while (n-- > 0) {
		*dst++ = *src++;
	}
}

int cnn_load_bias(void)
{
	memcpy_8to32((uint32_t *) 0x50108000, bias_0, sizeof(uint8_t) * 96);
	memcpy_8to32((uint32_t *) 0x50508000, bias_1, sizeof(uint8_t) * 96);
	memcpy_8to32((uint32_t *) 0x50908000, bias_2, sizeof(uint8_t) * 89);
	memcpy_8to32((uint32_t *) 0x50d08000, bias_3, sizeof(uint8_t) * 90);

	return CNN_OK;
}

int cnn_init(void)
{
	*((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
	*((volatile uint32_t *) 0x50100000) = 0x00100008; // Stop SM
	*((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
	*((volatile uint32_t *) 0x50100008) = 0x00000008; // Layer count
	*((volatile uint32_t *) 0x50500000) = 0x00100008; // Stop SM
	*((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
	*((volatile uint32_t *) 0x50500008) = 0x00000008; // Layer count
	*((volatile uint32_t *) 0x50900000) = 0x00100008; // Stop SM
	*((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
	*((volatile uint32_t *) 0x50900008) = 0x00000008; // Layer count
	*((volatile uint32_t *) 0x50d00000) = 0x00100008; // Stop SM
	*((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control
	*((volatile uint32_t *) 0x50d00008) = 0x00000008; // Layer count

	return CNN_OK;
}

int cnn_configure(void)
{
	// Layer 0 quadrant 0
	*((volatile uint32_t *) 0x50100010) = 0x00000063; // Rows
	*((volatile uint32_t *) 0x50100310) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50100590) = 0x00008b20; // Layer control
	*((volatile uint32_t *) 0x50100a10) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50100610) = 0x000000f8; // Mask offset and count
	*((volatile uint32_t *) 0x50100110) = 0x00001900; // 1D
	*((volatile uint32_t *) 0x50100790) = 0x00004000; // Post processing register
	*((volatile uint32_t *) 0x50100710) = 0x00010001; // Mask and processor enables

	// Layer 0 quadrant 1
	*((volatile uint32_t *) 0x50500010) = 0x00000063; // Rows
	*((volatile uint32_t *) 0x50500310) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50500590) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50500a10) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50500610) = 0x000000f8; // Mask offset and count
	*((volatile uint32_t *) 0x50500110) = 0x00001900; // 1D
	*((volatile uint32_t *) 0x50500790) = 0x00004000; // Post processing register

	// Layer 0 quadrant 2
	*((volatile uint32_t *) 0x50900010) = 0x00000063; // Rows
	*((volatile uint32_t *) 0x50900310) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50900590) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50900a10) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50900610) = 0x000000f8; // Mask offset and count
	*((volatile uint32_t *) 0x50900110) = 0x00001900; // 1D
	*((volatile uint32_t *) 0x50900790) = 0x00004000; // Post processing register

	// Layer 0 quadrant 3
	*((volatile uint32_t *) 0x50d00010) = 0x00000063; // Rows
	*((volatile uint32_t *) 0x50d00310) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50d00590) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50d00a10) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50d00610) = 0x000000f8; // Mask offset and count
	*((volatile uint32_t *) 0x50d00110) = 0x00001900; // 1D
	*((volatile uint32_t *) 0x50d00790) = 0x00005030; // Post processing register

	// Layer 1 quadrant 0
	*((volatile uint32_t *) 0x50100014) = 0x0000005b; // Rows
	*((volatile uint32_t *) 0x50100314) = 0x00010000; // SRAM write ptr
	*((volatile uint32_t *) 0x50100414) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50100514) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x50100594) = 0x00002b20; // Layer control
	*((volatile uint32_t *) 0x50100a14) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50100614) = 0x01200218; // Mask offset and count
	*((volatile uint32_t *) 0x50100114) = 0x00001800; // 1D
	*((volatile uint32_t *) 0x50100794) = 0x00001040; // Post processing register
	*((volatile uint32_t *) 0x50100714) = 0xffffffff; // Mask and processor enables

	// Layer 1 quadrant 1
	*((volatile uint32_t *) 0x50500014) = 0x0000005b; // Rows
	*((volatile uint32_t *) 0x50500314) = 0x00010000; // SRAM write ptr
	*((volatile uint32_t *) 0x50500414) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50500514) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x50500594) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50500a14) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50500614) = 0x01200218; // Mask offset and count
	*((volatile uint32_t *) 0x50500114) = 0x00001800; // 1D
	*((volatile uint32_t *) 0x50500714) = 0xffffffff; // Mask and processor enables

	// Layer 1 quadrant 2
	*((volatile uint32_t *) 0x50900014) = 0x0000005b; // Rows
	*((volatile uint32_t *) 0x50900314) = 0x00010000; // SRAM write ptr
	*((volatile uint32_t *) 0x50900414) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50900514) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x50900594) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50900a14) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50900614) = 0x01200218; // Mask offset and count
	*((volatile uint32_t *) 0x50900114) = 0x00001800; // 1D

	// Layer 1 quadrant 3
	*((volatile uint32_t *) 0x50d00014) = 0x0000005b; // Rows
	*((volatile uint32_t *) 0x50d00314) = 0x00010000; // SRAM write ptr
	*((volatile uint32_t *) 0x50d00414) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50d00514) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x50d00594) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50d00a14) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50d00614) = 0x01200218; // Mask offset and count
	*((volatile uint32_t *) 0x50d00114) = 0x00001800; // 1D

	// Layer 2 quadrant 0
	*((volatile uint32_t *) 0x50100018) = 0x00000054; // Rows
	*((volatile uint32_t *) 0x50100198) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x50100298) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x50100318) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50100418) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50100598) = 0x0000cba0; // Layer control
	*((volatile uint32_t *) 0x50100a18) = 0x00017800; // Layer control 2
	*((volatile uint32_t *) 0x50100618) = 0x00000178; // Mask offset and count
	*((volatile uint32_t *) 0x50100118) = 0x00001600; // 1D
	*((volatile uint32_t *) 0x50100798) = 0x00004000; // Post processing register

	// Layer 2 quadrant 1
	*((volatile uint32_t *) 0x50500018) = 0x00000054; // Rows
	*((volatile uint32_t *) 0x50500198) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x50500298) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x50500318) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50500418) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50500598) = 0x00000ba0; // Layer control
	*((volatile uint32_t *) 0x50500a18) = 0x00017800; // Layer control 2
	*((volatile uint32_t *) 0x50500618) = 0x00000178; // Mask offset and count
	*((volatile uint32_t *) 0x50500118) = 0x00001600; // 1D
	*((volatile uint32_t *) 0x50500798) = 0x00004000; // Post processing register

	// Layer 2 quadrant 2
	*((volatile uint32_t *) 0x50900018) = 0x00000054; // Rows
	*((volatile uint32_t *) 0x50900198) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x50900298) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x50900318) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50900418) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50900598) = 0x00000ba0; // Layer control
	*((volatile uint32_t *) 0x50900a18) = 0x00017800; // Layer control 2
	*((volatile uint32_t *) 0x50900618) = 0x00000178; // Mask offset and count
	*((volatile uint32_t *) 0x50900118) = 0x00001600; // 1D
	*((volatile uint32_t *) 0x50900798) = 0x00004000; // Post processing register
	*((volatile uint32_t *) 0x50900718) = 0xffffffff; // Mask and processor enables

	// Layer 2 quadrant 3
	*((volatile uint32_t *) 0x50d00018) = 0x00000054; // Rows
	*((volatile uint32_t *) 0x50d00198) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x50d00298) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x50d00318) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50d00418) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50d00598) = 0x00000ba0; // Layer control
	*((volatile uint32_t *) 0x50d00a18) = 0x00017800; // Layer control 2
	*((volatile uint32_t *) 0x50d00618) = 0x00000178; // Mask offset and count
	*((volatile uint32_t *) 0x50d00118) = 0x00001600; // 1D
	*((volatile uint32_t *) 0x50d00798) = 0x00005000; // Post processing register
	*((volatile uint32_t *) 0x50d00718) = 0xffffffff; // Mask and processor enables

	// Layer 3 quadrant 0
	*((volatile uint32_t *) 0x5010001c) = 0x00000024; // Rows
	*((volatile uint32_t *) 0x5010019c) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x5010029c) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x5010041c) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x5010051c) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x5010059c) = 0x00006ba0; // Layer control
	*((volatile uint32_t *) 0x50100a1c) = 0x0001f800; // Layer control 2
	*((volatile uint32_t *) 0x5010061c) = 0x03980590; // Mask offset and count
	*((volatile uint32_t *) 0x5010011c) = 0x00001510; // 1D
	*((volatile uint32_t *) 0x5010079c) = 0x00002000; // Post processing register
	*((volatile uint32_t *) 0x5010071c) = 0xffffffff; // Mask and processor enables

	// Layer 3 quadrant 1
	*((volatile uint32_t *) 0x5050001c) = 0x00000024; // Rows
	*((volatile uint32_t *) 0x5050019c) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x5050029c) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x5050041c) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x5050051c) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x5050059c) = 0x00000ba0; // Layer control
	*((volatile uint32_t *) 0x50500a1c) = 0x0001f800; // Layer control 2
	*((volatile uint32_t *) 0x5050061c) = 0x03980590; // Mask offset and count
	*((volatile uint32_t *) 0x5050011c) = 0x00001510; // 1D
	*((volatile uint32_t *) 0x5050079c) = 0x00003000; // Post processing register
	*((volatile uint32_t *) 0x5050071c) = 0xffffffff; // Mask and processor enables

	// Layer 3 quadrant 2
	*((volatile uint32_t *) 0x5090001c) = 0x00000024; // Rows
	*((volatile uint32_t *) 0x5090019c) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x5090029c) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x5090041c) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x5090051c) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x5090059c) = 0x00000ba0; // Layer control
	*((volatile uint32_t *) 0x50900a1c) = 0x0001f800; // Layer control 2
	*((volatile uint32_t *) 0x5090061c) = 0x03980590; // Mask offset and count
	*((volatile uint32_t *) 0x5090011c) = 0x00001510; // 1D
	*((volatile uint32_t *) 0x5090079c) = 0x00002000; // Post processing register
	*((volatile uint32_t *) 0x5090071c) = 0xffffffff; // Mask and processor enables

	// Layer 3 quadrant 3
	*((volatile uint32_t *) 0x50d0001c) = 0x00000024; // Rows
	*((volatile uint32_t *) 0x50d0019c) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x50d0029c) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x50d0041c) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50d0051c) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x50d0059c) = 0x00000ba0; // Layer control
	*((volatile uint32_t *) 0x50d00a1c) = 0x0001f800; // Layer control 2
	*((volatile uint32_t *) 0x50d0061c) = 0x03980590; // Mask offset and count
	*((volatile uint32_t *) 0x50d0011c) = 0x00001510; // 1D
	*((volatile uint32_t *) 0x50d0079c) = 0x00002000; // Post processing register

	// Layer 4 quadrant 0
	*((volatile uint32_t *) 0x50100020) = 0x0000000d; // Rows
	*((volatile uint32_t *) 0x50100320) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50100420) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x501005a0) = 0x0000eb20; // Layer control
	*((volatile uint32_t *) 0x50100a20) = 0x0001f800; // Layer control 2
	*((volatile uint32_t *) 0x50100620) = 0x05a00798; // Mask offset and count
	*((volatile uint32_t *) 0x50100120) = 0x00001500; // 1D
	*((volatile uint32_t *) 0x501007a0) = 0x00002000; // Post processing register
	*((volatile uint32_t *) 0x50100720) = 0xffffffff; // Mask and processor enables

	// Layer 4 quadrant 1
	*((volatile uint32_t *) 0x50500020) = 0x0000000d; // Rows
	*((volatile uint32_t *) 0x50500320) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50500420) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x505005a0) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50500a20) = 0x0001f800; // Layer control 2
	*((volatile uint32_t *) 0x50500620) = 0x05a00798; // Mask offset and count
	*((volatile uint32_t *) 0x50500120) = 0x00001500; // 1D
	*((volatile uint32_t *) 0x505007a0) = 0x00002000; // Post processing register
	*((volatile uint32_t *) 0x50500720) = 0xffffffff; // Mask and processor enables

	// Layer 4 quadrant 2
	*((volatile uint32_t *) 0x50900020) = 0x0000000d; // Rows
	*((volatile uint32_t *) 0x50900320) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50900420) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x509005a0) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50900a20) = 0x0001f800; // Layer control 2
	*((volatile uint32_t *) 0x50900620) = 0x05a00798; // Mask offset and count
	*((volatile uint32_t *) 0x50900120) = 0x00001500; // 1D
	*((volatile uint32_t *) 0x509007a0) = 0x00003000; // Post processing register
	*((volatile uint32_t *) 0x50900720) = 0xffffffff; // Mask and processor enables

	// Layer 4 quadrant 3
	*((volatile uint32_t *) 0x50d00020) = 0x0000000d; // Rows
	*((volatile uint32_t *) 0x50d00320) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50d00420) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50d005a0) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50d00a20) = 0x0001f800; // Layer control 2
	*((volatile uint32_t *) 0x50d00620) = 0x05a00798; // Mask offset and count
	*((volatile uint32_t *) 0x50d00120) = 0x00001500; // 1D
	*((volatile uint32_t *) 0x50d007a0) = 0x00002000; // Post processing register
	*((volatile uint32_t *) 0x50d00720) = 0xffffffff; // Mask and processor enables

	// Layer 5 quadrant 0
	*((volatile uint32_t *) 0x50100024) = 0x0001000b; // Rows
	*((volatile uint32_t *) 0x501001a4) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x501002a4) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x50100424) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50100524) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x501005a4) = 0x0000eaa0; // Layer control
	*((volatile uint32_t *) 0x50100a24) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50100624) = 0x09900a88; // Mask offset and count
	*((volatile uint32_t *) 0x50100124) = 0x00001400; // 1D
	*((volatile uint32_t *) 0x501007a4) = 0x00006000; // Post processing register
	*((volatile uint32_t *) 0x50100724) = 0xffffffff; // Mask and processor enables

	// Layer 5 quadrant 1
	*((volatile uint32_t *) 0x50500024) = 0x0001000b; // Rows
	*((volatile uint32_t *) 0x505001a4) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x505002a4) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x50500424) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50500524) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x505005a4) = 0x00000aa0; // Layer control
	*((volatile uint32_t *) 0x50500a24) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50500624) = 0x09900a88; // Mask offset and count
	*((volatile uint32_t *) 0x50500124) = 0x00001400; // 1D
	*((volatile uint32_t *) 0x505007a4) = 0x00007040; // Post processing register
	*((volatile uint32_t *) 0x50500724) = 0xffffffff; // Mask and processor enables

	// Layer 5 quadrant 2
	*((volatile uint32_t *) 0x50900024) = 0x0001000b; // Rows
	*((volatile uint32_t *) 0x509001a4) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x509002a4) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x50900424) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50900524) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x509005a4) = 0x00000aa0; // Layer control
	*((volatile uint32_t *) 0x50900a24) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50900624) = 0x09900a88; // Mask offset and count
	*((volatile uint32_t *) 0x50900124) = 0x00001400; // 1D
	*((volatile uint32_t *) 0x509007a4) = 0x00006000; // Post processing register
	*((volatile uint32_t *) 0x50900724) = 0xffffffff; // Mask and processor enables

	// Layer 5 quadrant 3
	*((volatile uint32_t *) 0x50d00024) = 0x0001000b; // Rows
	*((volatile uint32_t *) 0x50d001a4) = 0x00000001; // Pooling rows
	*((volatile uint32_t *) 0x50d002a4) = 0x00000001; // Stride
	*((volatile uint32_t *) 0x50d00424) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50d00524) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x50d005a4) = 0x00000aa0; // Layer control
	*((volatile uint32_t *) 0x50d00a24) = 0x0000f800; // Layer control 2
	*((volatile uint32_t *) 0x50d00624) = 0x09900a88; // Mask offset and count
	*((volatile uint32_t *) 0x50d00124) = 0x00001400; // 1D
	*((volatile uint32_t *) 0x50d007a4) = 0x00006000; // Post processing register
	*((volatile uint32_t *) 0x50d00724) = 0xffffffff; // Mask and processor enables

	// Layer 6 quadrant 0
	*((volatile uint32_t *) 0x50100328) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x501003a8) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x50100428) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x501005a8) = 0x00002b20; // Layer control
	*((volatile uint32_t *) 0x50100a28) = 0x0001f803; // Layer control 2
	*((volatile uint32_t *) 0x50100628) = 0x2ac032b8; // Mask offset and count
	*((volatile uint32_t *) 0x50100128) = 0x00000100; // 1D
	*((volatile uint32_t *) 0x501007a8) = 0x00001000; // Post processing register
	*((volatile uint32_t *) 0x50100728) = 0xffffffff; // Mask and processor enables

	// Layer 6 quadrant 1
	*((volatile uint32_t *) 0x50500328) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x505003a8) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x50500428) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x505005a8) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50500a28) = 0x0001f803; // Layer control 2
	*((volatile uint32_t *) 0x50500628) = 0x2ac032b8; // Mask offset and count
	*((volatile uint32_t *) 0x50500128) = 0x00000100; // 1D
	*((volatile uint32_t *) 0x50500728) = 0xffffffff; // Mask and processor enables

	// Layer 6 quadrant 2
	*((volatile uint32_t *) 0x50900328) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x509003a8) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x50900428) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x509005a8) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50900a28) = 0x0001f803; // Layer control 2
	*((volatile uint32_t *) 0x50900628) = 0x2ac032b8; // Mask offset and count
	*((volatile uint32_t *) 0x50900128) = 0x00000100; // 1D

	// Layer 6 quadrant 3
	*((volatile uint32_t *) 0x50d00328) = 0x00000800; // SRAM write ptr
	*((volatile uint32_t *) 0x50d003a8) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x50d00428) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50d005a8) = 0x00000b20; // Layer control
	*((volatile uint32_t *) 0x50d00a28) = 0x0001f803; // Layer control 2
	*((volatile uint32_t *) 0x50d00628) = 0x2ac032b8; // Mask offset and count
	*((volatile uint32_t *) 0x50d00128) = 0x00000100; // 1D

	// Layer 7 quadrant 0
	*((volatile uint32_t *) 0x5010032c) = 0x0001a000; // SRAM write ptr
	*((volatile uint32_t *) 0x501003ac) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x5010042c) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x5010052c) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x501005ac) = 0x0000e920; // Layer control
	*((volatile uint32_t *) 0x50100a2c) = 0x00004800; // Layer control 2
	*((volatile uint32_t *) 0x5010062c) = 0x33c03408; // Mask offset and count
	*((volatile uint32_t *) 0x5010012c) = 0x00000100; // 1D
	*((volatile uint32_t *) 0x501007ac) = 0x00002000; // Post processing register
	*((volatile uint32_t *) 0x5010072c) = 0xffffffff; // Mask and processor enables

	// Layer 7 quadrant 1
	*((volatile uint32_t *) 0x5050032c) = 0x0001a000; // SRAM write ptr
	*((volatile uint32_t *) 0x505003ac) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x5050042c) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x5050052c) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x505005ac) = 0x00000920; // Layer control
	*((volatile uint32_t *) 0x50500a2c) = 0x00004800; // Layer control 2
	*((volatile uint32_t *) 0x5050062c) = 0x33c03408; // Mask offset and count
	*((volatile uint32_t *) 0x5050012c) = 0x00000100; // 1D
	*((volatile uint32_t *) 0x505007ac) = 0x00002000; // Post processing register
	*((volatile uint32_t *) 0x5050072c) = 0xffffffff; // Mask and processor enables

	// Layer 7 quadrant 2
	*((volatile uint32_t *) 0x5090032c) = 0x0001a000; // SRAM write ptr
	*((volatile uint32_t *) 0x509003ac) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x5090042c) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x5090052c) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x509005ac) = 0x00000920; // Layer control
	*((volatile uint32_t *) 0x50900a2c) = 0x00004800; // Layer control 2
	*((volatile uint32_t *) 0x5090062c) = 0x33c03408; // Mask offset and count
	*((volatile uint32_t *) 0x5090012c) = 0x00000100; // 1D
	*((volatile uint32_t *) 0x509007ac) = 0x00002000; // Post processing register
	*((volatile uint32_t *) 0x5090072c) = 0xffffffff; // Mask and processor enables

	// Layer 7 quadrant 3
	*((volatile uint32_t *) 0x50d0032c) = 0x0001a000; // SRAM write ptr
	*((volatile uint32_t *) 0x50d003ac) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x50d0042c) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50d0052c) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x50d005ac) = 0x00000920; // Layer control
	*((volatile uint32_t *) 0x50d00a2c) = 0x00004800; // Layer control 2
	*((volatile uint32_t *) 0x50d0062c) = 0x33c03408; // Mask offset and count
	*((volatile uint32_t *) 0x50d0012c) = 0x00000100; // 1D
	*((volatile uint32_t *) 0x50d007ac) = 0x00003050; // Post processing register
	*((volatile uint32_t *) 0x50d0072c) = 0xffffffff; // Mask and processor enables

	// Layer 8 quadrant 0
	*((volatile uint32_t *) 0x50100330) = 0x00012400; // SRAM write ptr
	*((volatile uint32_t *) 0x501003b0) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x50100430) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50100530) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x501005b0) = 0x0000e920; // Layer control
	*((volatile uint32_t *) 0x50100a30) = 0x0000c000; // Layer control 2
	*((volatile uint32_t *) 0x50100630) = 0x34e035a0; // Mask offset and count
	*((volatile uint32_t *) 0x50100130) = 0x00000100; // 1D
	*((volatile uint32_t *) 0x501007b0) = 0x00002000; // Post processing register
	*((volatile uint32_t *) 0x50100730) = 0xffffffff; // Mask and processor enables

	// Layer 8 quadrant 1
	*((volatile uint32_t *) 0x50500330) = 0x00012400; // SRAM write ptr
	*((volatile uint32_t *) 0x505003b0) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x50500430) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50500530) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x505005b0) = 0x00000920; // Layer control
	*((volatile uint32_t *) 0x50500a30) = 0x0000c000; // Layer control 2
	*((volatile uint32_t *) 0x50500630) = 0x34e035a0; // Mask offset and count
	*((volatile uint32_t *) 0x50500130) = 0x00000100; // 1D
	*((volatile uint32_t *) 0x505007b0) = 0x00002000; // Post processing register
	*((volatile uint32_t *) 0x50500730) = 0xffffffff; // Mask and processor enables

	// Layer 8 quadrant 2
	*((volatile uint32_t *) 0x50900330) = 0x00012400; // SRAM write ptr
	*((volatile uint32_t *) 0x509003b0) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x50900430) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50900530) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x509005b0) = 0x00000920; // Layer control
	*((volatile uint32_t *) 0x50900a30) = 0x0000c000; // Layer control 2
	*((volatile uint32_t *) 0x50900630) = 0x34e035a0; // Mask offset and count
	*((volatile uint32_t *) 0x50900130) = 0x00000100; // 1D
	*((volatile uint32_t *) 0x509007b0) = 0x00003040; // Post processing register
	*((volatile uint32_t *) 0x50900730) = 0xffffffff; // Mask and processor enables

	// Layer 8 quadrant 3
	*((volatile uint32_t *) 0x50d00330) = 0x00012400; // SRAM write ptr
	*((volatile uint32_t *) 0x50d003b0) = 0x00000001; // Write ptr time slot offs
	*((volatile uint32_t *) 0x50d00430) = 0x00002000; // Write ptr mask offs
	*((volatile uint32_t *) 0x50d00530) = 0x00000800; // SRAM read ptr
	*((volatile uint32_t *) 0x50d005b0) = 0x00000920; // Layer control
	*((volatile uint32_t *) 0x50d00a30) = 0x0000c000; // Layer control 2
	*((volatile uint32_t *) 0x50d00630) = 0x34e035a0; // Mask offset and count
	*((volatile uint32_t *) 0x50d00130) = 0x00000100; // 1D
	*((volatile uint32_t *) 0x50d007b0) = 0x00002000; // Post processing register
	*((volatile uint32_t *) 0x50d00730) = 0xffffffff; // Mask and processor enables


	return CNN_OK;
}

int cnn_start(void)
{
	cnn_time = 0;

	*((volatile uint32_t *) 0x50100000) = 0x00100808; // Enable quadrant 0
	*((volatile uint32_t *) 0x50500000) = 0x00100809; // Enable quadrant 1
	*((volatile uint32_t *) 0x50900000) = 0x00100809; // Enable quadrant 2
	*((volatile uint32_t *) 0x50d00000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
	MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

	CNN_START; // Allow capture of processing time
	*((volatile uint32_t *) 0x50100000) = 0x00100009; // Master enable quadrant 0

	return CNN_OK;
}

int cnn_unload(int8_t *states, int8_t *quantiles)
{
	uint8_t *out_buf = (uint8_t *) states;
	uint32_t val;
	volatile uint32_t *addr;
	int i;

	// Custom unload for this network, layer 7: 8-bit data, shape: (10, 1, 1)
	addr = (volatile uint32_t *) 0x51008000;
	for (i = 0; i < 3; i++) {
		val = *addr;
		addr += 0x2000;
		if (i == 2) {
			*out_buf++ = val & 0xff;
			*out_buf++ = (val >> 8) & 0xff;
		} else {
			*out_buf++ = val & 0xff;
			*out_buf++ = (val >> 8) & 0xff;
			*out_buf++ = (val >> 16) & 0xff;
			*out_buf++ = (val >> 24) & 0xff;
		}

	}

	// Custom unload for this network, layer 8: 8-bit data, shape: (25, 1, 1)
	out_buf = ((uint8_t *) quantiles);
	addr = (volatile uint32_t *) 0x50c09000;
	for (i = 0; i < 3; i++) {
		val = *addr;
		addr += 0x2000;
		*out_buf++ = val & 0xff;
		*out_buf++ = (val >> 8) & 0xff;
		*out_buf++ = (val >> 16) & 0xff;
		*out_buf++ = (val >> 24) & 0xff;
	}
	addr = (volatile uint32_t *) 0x51001000;
	for (i = 0; i < 4; i++) {
		val = *addr;
		addr += 0x2000;
		if (i == 3) {
			*out_buf++ = val & 0xff;
		} else {
			*out_buf++ = val & 0xff;
			*out_buf++ = (val >> 8) & 0xff;
			*out_buf++ = (val >> 16) & 0xff;
			*out_buf++ = (val >> 24) & 0xff;
		}
	}

	return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
	// Reset all domains, restore power to CNN
	MXC_GCFR->reg3 = 0xf; // Reset
	MXC_GCFR->reg1 = 0xf; // Mask memory
	MXC_GCFR->reg0 = 0xf; // Power
	MXC_GCFR->reg2 = 0x0; // Iso
	MXC_GCFR->reg3 = 0x0; // Reset

	MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
										 | clock_divider | clock_source;
	MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

	MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

	return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
	mxc_gpio_cfg_t gpio_out;
	gpio_out.port = port;
	gpio_out.mask = pin;
	gpio_out.pad = MXC_GPIO_PAD_NONE;
	gpio_out.func = MXC_GPIO_FUNC_OUT;
	MXC_GPIO_Config(&gpio_out);
	MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

	return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
	mxc_gpio_cfg_t gpio_out;
	gpio_out.port = port;
	gpio_out.mask = pin;
	gpio_out.pad = MXC_GPIO_PAD_NONE;
	gpio_out.func = MXC_GPIO_FUNC_OUT;
	MXC_GPIO_Config(&gpio_out);
	MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

	return CNN_OK;
}

int cnn_disable(void)
{
	// Disable CNN clock
	MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

	// Disable power to CNN
	MXC_GCFR->reg3 = 0xf; // Reset
	MXC_GCFR->reg2 |= 0xf; // Iso
	MXC_GCFR->reg0 = 0x0; // Power
	MXC_GCFR->reg1 = 0x0; // Mask memory
	MXC_GCFR->reg3 = 0x0; // Reset

	return CNN_OK;
}

